name: first workflow

on: 
  push:
    branches: main 
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
     - uses: actions/checkout@v3
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v3
       with:
        python-version: ${{ matrix.python-version }}
     - name: Install dependencies
       run: |
        python -m pip install --upgrade pip
        python -m pip install behave
        python -m pip install playwright
        python -m playwright install
        python -m pip install allure-behave
        python -m pip install python-dotenv
    
     - name: Run tests
       run: |
         python runner_behave.py
         
     # - name: Copy PDF baseline files
     #   uses: dmnemec/copy_file_to_another_repo_action@main
     #   env:
     #     API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
     #   with:
     #     source_file: "PDF_compiler"
     #     destination_repo: ${{ github.repository }}
     #     destination_branch: "main"
     #     destination_folder: ${{ github.run_number }}
     #     user_email: "sudhanshupandey848@gmail.com"
     #     user_name: "sudhanshupandey123"
     #     commit_message: "Copy main"

     # - name: Copy Behave log files
     #   uses: dmnemec/copy_file_to_another_repo_action@main
     #   env:
     #     API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
     #   with:
     #     source_file: "reports/behave.log"
     #     destination_repo: ${{ github.repository }}
     #     destination_branch: "behave-logs"
     #     destination_folder: ${{ github.run_number }}
     #     user_email: "manoj.patil@atlascopco.com"
     #     user_name: "manojatlas"
     #     commit_message: "Behave log file for build"

     - name: Get Allure history
       uses: actions/checkout@v2
       if: always()
       continue-on-error: true
       with:
         ref: gh-pages
         path: gh-pages

     - name: Test marketplace action
       uses: simple-elf/allure-report-action@master
       if: always()
       id: allure-report
       with:
          allure_results: reports
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

     - name: Deploy report to Github Pages
       if: always()
       uses: peaceiris/actions-gh-pages@v2
       env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
